# kafka-kraft-deployment.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  # KAFKA_CFG_NODE_ID: "1"
  # KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  # KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
  # KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  # # Adding EXTERNAL listener on 9094
  # KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
  # KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
  # KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
  # KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  # KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  
  KAFKA_ENABLE_KRAFT: "yes"
  KAFKA_CFG_PROCESS_ROLES: "broker,controller"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092,EXTERNAL://kafka_b:9094"
  KAFKA_BROKER_ID: "1"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@127.0.0.1:9093"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_CFG_NODE_ID: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  BITNAMI_DEBUG: "yes"
  KAFKA_CFG_NUM_PARTITIONS: "2"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    service: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka
  template:
    metadata:
      labels:
        service: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 9093
          name: controller
        - containerPort: 9094
          name: external
        envFrom:
        - configMapRef:
            name: kafka-config
        env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: KAFKA_ENABLE_KRAFT
          value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    service: kafka
spec:
  ports:
  - name: kafka
    port: 9092
    targetPort: kafka
  - name: external
    port: 9094
    targetPort: external
  selector:
    app: kafka
  type: ClusterIP
---
# Optional NodePort service for external access
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  labels:
    service: kafka
spec:
  ports:
  - name: external
    port: 9094
    targetPort: external
    nodePort: 30094
  selector:
    app: kafka
  type: NodePort